### ISSUE TITLE
Having trouble with getting started

### ISSUE THREAD

**Issue by ocampogarcia** [TiedNets/TiedNets#6]
Hi there,

I downloaded the whole repository, and I am trying to run the examples provided in the Wiki. I am trying to use the run function of the module netw_creator, but the following error comes up. TiedNets is the master folder where I saved your repository, and I am using Python 3.7.10. Is there something that I am doing wrong? Thank you.

import TiedNets
from TiedNets import netw_creator

Traceback (most recent call last):

  File "C:\python37\lib\site-packages\IPython\core\interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "C:\Users\johno\AppData\Local\Temp/ipykernel_18208/1024418120.py", line 2, in <module>
    from TiedNets import netw_creator

  File "c:\Users\johno\OneDrive\Desktop\Codes\TiedNets\netw_creator.py", line 937
    centrality_by_node = OrderedDict(sorted(centrality_by_node.items(), key=lambda (k, v): (v, k)))
                                                                                   ^
SyntaxError: invalid syntax

**Comment by AgostinoSturaro** [comment]
You need to use Python 2.7 and an older version of NetworkX.

You can try to download an old version of Anaconda2, which has Python 2 and the libraries you need.
The latest Anaconda2 seems to be Anaconda2-5.3.1
https://repo.anaconda.com/archive/

Check this issue for more info.
https://github.com/TiedNets/TiedNets/issues/3

Also, don't run this from a OneDrive folder.
The run produces a lot of files and if OneDrive starts to synchronize them it will likely mess things up.

I still have to update this project and cleanup old files, but the latest version with more examples is on this branch.
https://github.com/TiedNets/TiedNets/tree/create_nets_conf

**Comment by ocampogarcia** [comment]
Thank you for your reply!
